# Introduction

Hierarchical linear modeling (HLM) is a powerful and flexible statistical framework for analyzing complex nested relationships. In education, for example, we may be interested in factors that affect student achievement. Broadly, we may theorize factors associated with the school (school social groups, principal leadership, school size), the teachers (effectiveness of the teacher, specific expertise of the teacher, relationship of the teacher with the student), and the students themselves (motivation, previous achievement, general intelligence). Each of these factors associated with student achievement could be conceptualized as different “levels” of nesting – students (at Level 1) are nested within classrooms (at Level 2), which are nested within schools (at Level 3) – in which each level potentially impacts student achievement. HLM allows researchers to investigate these nested relationships and either parse them out (i.e., control for higher-level factors to examine the unique effect of a specific variable) or examine the impact of variables at the higher levels (e.g., the effect of attending public versus private school on student achievement). HLM is used across a variety of disciplines to examine multilevel effects. For example, in organizational research one may investigate how employee interactions differ by the type of organization the employees belong to (e.g., corporate compared to local). In this paper, however, I will be focusing exclusively on the application of HLM to educational research. 

HLM is particularly well suited for evaluating changes in student achievement through growth models applied to longitudinal data. These growth models can be used to evaluate how individuals are changing over time, and how specific variables at any level predict where the individuals begin and/or the rate at which they change. For example, we could examine data from a cohort of students as they moved from kindergarten through grade 5 in urban and rural schools. We could then test whether the achievement of students attending urban schools differed significantly in kindergarten from students attending rural schools, and whether these same students differed in the rate at which they progressed during the 5 years of the study. We could also examine other characteristics of the students. For example, we could examine the rate at which students with one specific disability (e.g., autism spectrum disorder) progressed as compared to students with a different disability (e.g., learning disabled), and whether this observed relationship held for students in both urban and rural schools. Growth models are discussed in Chapter 3 of this manuscript, while cross-sectional models (i.e., one point in time) are discussed in Chapter 2.

The purpose of this paper is to introduce readers to the core concepts of HLM as applied to cross-sectional and longitudinal data. HLM is a complex topic and no assumptions are made about readers’ familiarity with the topic outside of a basic understanding of regression. Thus, the bulk of this paper is dedicated to interpreting HLM analyses and important decisions that analysts make when building complex models. In Chapter 2, I begin with a brief explanation of nested data structures and some of the problems they pose. The primary components of a two-level model with cross-sectional data are then introduced and important elements of consideration discussed. In this section, the basic notation used for the null or unconditional model (no predictor variables) is introduced, as well as how it can be extended to include predictor variables. Model building and important statistics accompanying HLM analyses are also discussed, including overall model fit, the intraclass correlation coefficient (ICC), and the Pseudo R2 statistic. All the basic concepts of HLM are introduced in this section, which is concluded with an illustrated example using real data. 
	The bulk of the paper is dedicated to Chapter 3, where the principles introduced for cross-sectional data are extended to illustrate how the concept of nesting can be used to measure growth by treating time as nested within a student. In other words, just as many students may be nested within a school in a model with cross-sectional data, so too can multiple test scores be nested within an individual with longitudinal data. A two-level growth model is first introduced. It is then shown how the notation and model-building strategies can be expanded to three-levels. Considerable time is taken in Chapter 3 to reflect on specific issues related to growth modeling, including the linearity of the slope, the coding of time, and covariates that may vary by time. 

It is important to note that this paper is intended to be educative for consumers of research – not for researchers intending to apply the techniques. However, HLM notation is discussed in considerable detail given that it is critical to understanding the specific model that has been applied. As stated earlier, it is also assumed that readers have a basic understanding of regression. For readers not yet familiar with regression, I recommend reading the first two sections of the structural equation modeling manuscript from this series (Anderson, Patarapichayatham, & Nese, 2013). Because the intended audience of this paper is consumers of research, and not researchers, there will be some issues that will be covered in less depth than interested readers may prefer. For those interested in more detailed accounts of the topics presented here, I recommend Raudenbush and Bryk (2002), Hox (2010), and (Snijders & Bosker, 2011) for a comprehensive overview of HLM and Singer and Willett (2003) for more detail surrounding analyses with longitudinal data. Finally, it is worth mentioning that readers completely unfamiliar with HLM may not follow every detail of the illustrated examples. One should not be concerned if this is the case. I opted to be overly inclusive in the examples, rather than gloss over important elements of the analysis, reasoning that more advanced readers may be interested in the model building decisions. 